# Generated by Django 4.2.6 on 2023-11-02 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

woman_photo1 = 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzHMDlwRCHOHZP_tX7jRYNxV8W8MpNEog45w&usqp=CAU'
woman_photo2 = 'https://marketplace.canva.com/EAFqNrAJpQs/1/0/1600w/canva-neutral-pink-modern-circle-shape-linkedin-profile-picture-WAhofEY5L1U.jpg'
man_photo1 = 'https://images.unsplash.com/photo-1480455624313-e29b44bbfde1?auto=format&fit=crop&q=80&w=1000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8bWFsZSUyMHByb2ZpbGV8ZW58MHx8MHx8fDA%3D'
man_photo2 = 'https://www.elitesingles.co.uk/wp-content/uploads/sites/59/2019/11/2b_en_articleslide_sm2-350x264.jpg'


def new_employee(Employee, User, username, password, department, role, first_name, last_name, photo_link,
                 is_admin=False):
    user = User.objects.create_user(username=username, password=password, is_staff=is_admin, is_superuser=is_admin,
                                    first_name=first_name, last_name=last_name)
    user.save()
    employee = Employee.objects.create(user=user, department=department, role=role, photo_link=photo_link)
    employee.save()


def populate_common(apps, schema_editor):
    Employee = apps.get_model('common', 'Employee')
    User = apps.get_model('auth', 'User')
    new_employee(Employee, User, username='admin', password='root', department='IT', role='IT Manager',
                 first_name='Carlo', last_name='Olivera', is_admin=True, photo_link=man_photo2)
    new_employee(Employee, User, username='it_tech1', password='root', department='IT', role='IT Technical',
                 first_name='Marcela', last_name='Garcia', photo_link=woman_photo2)
    new_employee(Employee, User, username='it_tech2', password='root', department='IT', role='IT Technical',
                 first_name='Juan', last_name='Dario', photo_link=man_photo1)
    new_employee(Employee, User, username='caretaker_chief', password='root', department='Security',
                 role='Caretakers Manager', first_name='Angel', last_name='Morelos', photo_link=man_photo2)
    new_employee(Employee, User, username='caretaker1', password='root', department='Security', role='Caretaker',
                 first_name='Luz', last_name='Herrera', photo_link=woman_photo2)
    new_employee(Employee, User, username='caretaker2', password='root', department='Security', role='Caretaker',
                 first_name='Marco', last_name='Garcia', photo_link=man_photo1)
    new_employee(Employee, User, username='administrative_manager', password='root', department='Administrative',
                 role='Administrative Manager', first_name='Regina', last_name='Uribe', photo_link=woman_photo2)
    new_employee(Employee, User, username='administrative1', password='root', department='Administrative',
                 role='Administrative', first_name='Lucero', last_name='Uribe', photo_link=woman_photo1)
    new_employee(Employee, User, username='administrative2', password='root', department='Administrative',
                 role='Administrative', first_name='Maria', last_name='Arteaga', photo_link=woman_photo1)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(
                    choices=[('IT', 'It'), ('Administrative', 'Administrative'), ('Operations', 'Operations'),
                             ('Collection', 'Collection'), ('Research', 'Research'), ('Education', 'Education'),
                             ('Preservation', 'Preservation'), ('Security', 'Security'), ('External', 'External')],
                    default='External', max_length=30)),
                ('state', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE',
                                           max_length=30)),
                ('role', models.CharField(choices=[('IT Manager', 'It Manager'), ('IT Technical', 'It Technical'),
                                                   ('Caretakers Manager', 'Caretaker Chief'),
                                                   ('Caretaker', 'Caretaker'),
                                                   ('Administrative Manager', 'Administrative Manager'),
                                                   ('Administrative', 'Administrative'),
                                                   ('Operations Manager', 'Operations Manager'),
                                                   ('Cleaning', 'Cleaning'), ('Maintenance', 'Maintenance'),
                                                   ('Salesman', 'Salesman'), ('Ticket Taker', 'Ticket Taker'), (
                                                       'Collection, Research & Education Manager',
                                                       'Collection Research Education Manager'),
                                                   ('Educator', 'Educator'),
                                                   ('Tour Guide', 'Tour Guide'), ('Researcher', 'Researcher'),
                                                   ('Preservation Manager', 'Preservation Manager'),
                                                   ('Restorer', 'Restorer'), ('Curator', 'Curator'), ('Idle', 'Idle')],
                                          default='Idle', max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('photo_link', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(populate_common),
    ]
