# Generated by Django 4.2.6 on 2023-12-10 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.core.management import call_command


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(
                    choices=[('IT', 'It'), ('Administrative', 'Administrative'), ('Operations', 'Operations'),
                             ('Collection', 'Collection'), ('Research', 'Research'), ('Education', 'Education'),
                             ('Preservation', 'Preservation'), ('Security', 'Security'), ('External', 'External')],
                    default='External', max_length=30)),
                ('state', models.CharField(
                    choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('In Holidays', 'Holidays'),
                             ('Maternity', 'Maternity'), ('Paternity', 'Paternity'), ('Sick', 'Sick')],
                    default='Active', max_length=30)),
                ('role', models.CharField(choices=[('IT Manager', 'It Manager'), ('IT Technical', 'It Technical'),
                                                   ('Caretakers Manager', 'Caretaker Chief'),
                                                   ('Caretaker', 'Caretaker'),
                                                   ('Administrative Manager', 'Administrative Manager'),
                                                   ('Administrative', 'Administrative'),
                                                   ('Operations Manager', 'Operations Manager'),
                                                   ('Cleaning', 'Cleaning'), ('Maintenance', 'Maintenance'),
                                                   ('Salesman', 'Salesman'), ('Ticket Taker', 'Ticket Taker'), (
                                                       'Collection, Research & Education Manager',
                                                       'Collection Research Education Manager'),
                                                   ('Educator', 'Educator'),
                                                   ('Tour Guide', 'Tour Guide'), ('Researcher', 'Researcher'),
                                                   ('Preservation Manager', 'Preservation Manager'),
                                                   ('Restorer', 'Restorer'), ('Curator', 'Curator'), ('Idle', 'Idle')],
                                          default='Idle', max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('birthday', models.DateField()),
                ('country', models.CharField(default='Mexico', max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('zip', models.PositiveIntegerField()),
                ('street', models.CharField(max_length=100)),
                ('settlement', models.CharField(max_length=100)),
                ('ext', models.PositiveIntegerField()),
                ('int', models.PositiveIntegerField()),
                ('phone', models.PositiveIntegerField()),
                ('cellphone', models.PositiveIntegerField()),
                ('bachelor_degree', models.CharField(max_length=100)),
                (
                    'user',
                    models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('cv', models.FileField(upload_to='')),
                ('address_proof', models.FileField(upload_to='')),
                ('id_proof', models.FileField(upload_to='')),
                ('bachelors_degree_proof', models.FileField(upload_to='')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='common.employee')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NSS', models.PositiveIntegerField()),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='common.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateMedicalInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to='')),
                ('medical_file',
                 models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='common.medicalfiles')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy', models.CharField(max_length=100)),
                ('medical_file',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.medicalfiles')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalAilment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ailment', models.CharField(max_length=100)),
                ('medical_file',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.medicalfiles')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('description', models.CharField(max_length=1000)),
                ('employee_letter', models.FileField(null=True, upload_to='')),
                ('museum_letter', models.FileField(null=True, upload_to='')),
                ('drop_type', models.CharField(choices=[('Resignation', 'Resignation'), ('Dismissal', 'Dismissal')],
                                               default='Resignation', max_length=100)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='common.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDocumentsCertificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='')),
                ('employee_documents',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.employeedocuments')),
            ],
        ),
        migrations.CreateModel(
            name='DropProofs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('employee_drop',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.employeedrop')),
            ],
        ),
    ]
