# Generated by Django 4.2.6 on 2024-01-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_remove_employee_end_journey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bank',
            field=models.CharField(default='Banamex', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_account',
            field=models.PositiveIntegerField(default=123456789012345678),
        ),
        migrations.AddField(
            model_name='employee',
            name='clabe',
            field=models.PositiveIntegerField(default=123456789012345678),
        ),
        migrations.AddField(
            model_name='employee',
            name='end_journey',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='init_journey',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
