# Generated by Django 4.2.6 on 2023-12-10 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=50, unique=True)),
                ('open_date', models.DateTimeField(auto_now_add=True)),
                ('channel_description', models.CharField(max_length=1000)),
                ('chat_type', models.CharField(choices=[('PUBLIC', 'Public'), ('GROUP', 'Group'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=30)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChannelMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_content', models.CharField(max_length=1000)),
                ('send_date', models.DateTimeField(auto_now_add=True)),
                ('drop_date', models.DateTimeField(blank=True, null=True)),
                ('document', models.CharField(blank=True, max_length=1000, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat.chatchannel')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat.chatchannel')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.employee')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat.chatchannel')),
            ],
        ),
    ]
